<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\IOUBookingMaster;
use Faker\Generator as Faker;

$factory->define(IOUBookingMaster::class, function (Faker $faker) {

    return [
        'documentID' => $faker->word,
        'serialNo' => $faker->randomDigitNotNull,
        'iouVoucherAutoID' => $faker->randomDigitNotNull,
        'bookingCode' => $faker->word,
        'bookingDate' => $faker->word,
        'pullFromFuelYN' => $faker->randomDigitNotNull,
        'empID' => $faker->randomDigitNotNull,
        'empName' => $faker->word,
        'userType' => $faker->randomDigitNotNull,
        'comments' => $faker->text,
        'submittedYN' => $faker->randomDigitNotNull,
        'submittedDate' => $faker->date('Y-m-d H:i:s'),
        'submittedEmpID' => $faker->randomDigitNotNull,
        'confirmedYN' => $faker->randomDigitNotNull,
        'confirmedByEmpID' => $faker->randomDigitNotNull,
        'confirmedByName' => $faker->word,
        'confirmedDate' => $faker->date('Y-m-d H:i:s'),
        'approvedYN' => $faker->randomDigitNotNull,
        'approvedByEmpID' => $faker->randomDigitNotNull,
        'approvedByEmpName' => $faker->word,
        'approvedDate' => $faker->date('Y-m-d H:i:s'),
        'approvalComments' => $faker->word,
        'transactionCurrencyID' => $faker->randomDigitNotNull,
        'transactionCurrency' => $faker->word,
        'transactionExchangeRate' => $faker->randomDigitNotNull,
        'transactionCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'transactionAmount' => $faker->randomDigitNotNull,
        'companyLocalCurrencyID' => $faker->randomDigitNotNull,
        'companyLocalCurrency' => $faker->word,
        'companyLocalExchangeRate' => $faker->randomDigitNotNull,
        'companyLocalAmount' => $faker->randomDigitNotNull,
        'companyLocalCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'companyReportingCurrencyID' => $faker->randomDigitNotNull,
        'companyReportingCurrency' => $faker->word,
        'companyReportingExchangeRate' => $faker->randomDigitNotNull,
        'companyReportingAmount' => $faker->randomDigitNotNull,
        'companyReportingCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'empCurrencyID' => $faker->randomDigitNotNull,
        'empCurrency' => $faker->word,
        'empCurrencyExchangeRate' => $faker->randomDigitNotNull,
        'empCurrencyAmount' => $faker->randomDigitNotNull,
        'empCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'isDeleted' => $faker->randomDigitNotNull,
        'deletedEmpID' => $faker->randomDigitNotNull,
        'deletedDate' => $faker->date('Y-m-d H:i:s'),
        'currentLevelNo' => $faker->randomDigitNotNull,
        'companyFinanceYearID' => $faker->randomDigitNotNull,
        'companyFinanceYear' => $faker->word,
        'FYBegin' => $faker->word,
        'FYEnd' => $faker->word,
        'FYPeriodDateFrom' => $faker->word,
        'FYPeriodDateTo' => $faker->word,
        'companyFinancePeriodID' => $faker->randomDigitNotNull,
        'companyID' => $faker->randomDigitNotNull,
        'companyCode' => $faker->word,
        'segmentID' => $faker->randomDigitNotNull,
        'segmentCode' => $faker->word,
        'createdUserGroup' => $faker->randomDigitNotNull,
        'createdPCID' => $faker->word,
        'createdUserID' => $faker->word,
        'createdDateTime' => $faker->date('Y-m-d H:i:s'),
        'createdUserName' => $faker->word,
        'modifiedPCID' => $faker->word,
        'modifiedUserID' => $faker->word,
        'modifiedDateTime' => $faker->date('Y-m-d H:i:s'),
        'modifiedUserName' => $faker->word,
        'timestamp' => $faker->date('Y-m-d H:i:s')
    ];
});
