<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\POSStagMenuSalesItem;
use Faker\Generator as Faker;

$factory->define(POSStagMenuSalesItem::class, function (Faker $faker) {

    return [
        'wareHouseAutoID' => $faker->randomDigitNotNull,
        'menuSalesID' => $faker->randomDigitNotNull,
        'menuID' => $faker->randomDigitNotNull,
        'menuCategoryID' => $faker->randomDigitNotNull,
        'warehouseMenuID' => $faker->randomDigitNotNull,
        'warehouseMenuCategoryID' => $faker->randomDigitNotNull,
        'defaultUOM' => $faker->word,
        'unitOfMeasure' => $faker->word,
        'conversionRateUOM' => $faker->randomDigitNotNull,
        'qty' => $faker->randomDigitNotNull,
        'menuSalesPrice' => $faker->randomDigitNotNull,
        'salesPriceSubTotal' => $faker->randomDigitNotNull,
        'salesPriceAfterDiscount' => $faker->randomDigitNotNull,
        'salesPriceNetTotal' => $faker->randomDigitNotNull,
        'netRevenueTotal' => $faker->randomDigitNotNull,
        'totalMenuTaxAmount' => $faker->randomDigitNotNull,
        'totalMenuTaxAmountAfterDiscount' => $faker->randomDigitNotNull,
        'totalMenuServiceCharge' => $faker->randomDigitNotNull,
        'totalMenuServiceChargeAfterDiscount' => $faker->randomDigitNotNull,
        'discountPer' => $faker->randomDigitNotNull,
        'discountAmount' => $faker->randomDigitNotNull,
        'menuCost' => $faker->randomDigitNotNull,
        'kotID' => $faker->randomDigitNotNull,
        'kitchenNote' => $faker->word,
        'KOTAlarm' => $faker->randomDigitNotNull,
        'KOTFrontPrint' => $faker->randomDigitNotNull,
        'KOTStartDateTime' => $faker->date('Y-m-d H:i:s'),
        'KOTEndDateTime' => $faker->date('Y-m-d H:i:s'),
        'KOTDoneByEmpID' => $faker->randomDigitNotNull,
        'parentMenuSalesItemID' => $faker->randomDigitNotNull,
        'isSamplePrinted' => $faker->randomDigitNotNull,
        'TAXpercentage' => $faker->randomDigitNotNull,
        'TAXAmount' => $faker->randomDigitNotNull,
        'taxMasterID' => $faker->randomDigitNotNull,
        'isTaxEnabled' => $faker->randomDigitNotNull,
        'transactionCurrencyID' => $faker->randomDigitNotNull,
        'transactionCurrency' => $faker->word,
        'transactionAmount' => $faker->randomDigitNotNull,
        'transactionCurrencyDecimalPlaces' => $faker->word,
        'transactionExchangeRate' => $faker->randomDigitNotNull,
        'companyLocalCurrencyID' => $faker->randomDigitNotNull,
        'companyLocalCurrency' => $faker->word,
        'companyLocalAmount' => $faker->randomDigitNotNull,
        'companyLocalExchangeRate' => $faker->randomDigitNotNull,
        'companyLocalCurrencyDecimalPlaces' => $faker->word,
        'companyReportingCurrencyID' => $faker->randomDigitNotNull,
        'companyReportingCurrency' => $faker->word,
        'companyReportingAmount' => $faker->randomDigitNotNull,
        'companyReportingCurrencyDecimalPlaces' => $faker->word,
        'companyReportingExchangeRate' => $faker->randomDigitNotNull,
        'isOrderPending' => $faker->randomDigitNotNull,
        'isOrderInProgress' => $faker->randomDigitNotNull,
        'isOrderCompleted' => $faker->randomDigitNotNull,
        'companyID' => $faker->randomDigitNotNull,
        'companyCode' => $faker->word,
        'revenueGLAutoID' => $faker->randomDigitNotNull,
        'remarkes' => $faker->text,
        'createdUserGroup' => $faker->randomDigitNotNull,
        'createdPCID' => $faker->word,
        'createdUserID' => $faker->word,
        'createdDateTime' => $faker->date('Y-m-d H:i:s'),
        'createdUserName' => $faker->word,
        'modifiedPCID' => $faker->word,
        'modifiedUserID' => $faker->word,
        'modifiedDateTime' => $faker->date('Y-m-d H:i:s'),
        'modifiedUserName' => $faker->word,
        'timestamp' => $faker->date('Y-m-d H:i:s'),
        'is_sync' => $faker->randomDigitNotNull,
        'id_store' => $faker->randomDigitNotNull,
        'isUpdated' => $faker->randomDigitNotNull,
        'transaction_log_id' => $faker->randomDigitNotNull
    ];
});
