<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\POSSTAGInvoice;
use Faker\Generator as Faker;

$factory->define(POSSTAGInvoice::class, function (Faker $faker) {

    return [
        'documentSystemCode' => $faker->word,
        'documentCode' => $faker->word,
        'serialNo' => $faker->randomDigitNotNull,
        'invoiceSequenceNo' => $faker->randomDigitNotNull,
        'invoiceCode' => $faker->word,
        'isGroupBasedTax' => $faker->randomDigitNotNull,
        'customerID' => $faker->randomDigitNotNull,
        'customerCode' => $faker->word,
        'counterID' => $faker->randomDigitNotNull,
        'shiftID' => $faker->randomDigitNotNull,
        'memberID' => $faker->word,
        'memberName' => $faker->word,
        'invoiceDate' => $faker->word,
        'subTotal' => $faker->randomDigitNotNull,
        'discountPer' => $faker->randomDigitNotNull,
        'discountAmount' => $faker->randomDigitNotNull,
        'generalDiscountPercentage' => $faker->randomDigitNotNull,
        'generalDiscountAmount' => $faker->randomDigitNotNull,
        'netTotal' => $faker->randomDigitNotNull,
        'paidAmount' => $faker->randomDigitNotNull,
        'balanceAmount' => $faker->randomDigitNotNull,
        'cashAmount' => $faker->randomDigitNotNull,
        'chequeAmount' => $faker->randomDigitNotNull,
        'chequeNo' => $faker->word,
        'chequeDate' => $faker->word,
        'cardAmount' => $faker->randomDigitNotNull,
        'creditNoteID' => $faker->randomDigitNotNull,
        'creditNoteAmount' => $faker->randomDigitNotNull,
        'cardNumber' => $faker->randomDigitNotNull,
        'cardRefNo' => $faker->randomDigitNotNull,
        'cardBank' => $faker->randomDigitNotNull,
        'isCreditSales' => $faker->randomDigitNotNull,
        'creditSalesAmount' => $faker->randomDigitNotNull,
        'wareHouseAutoID' => $faker->randomDigitNotNull,
        'transactionCurrencyID' => $faker->randomDigitNotNull,
        'transactionCurrency' => $faker->word,
        'transactionExchangeRate' => $faker->randomDigitNotNull,
        'transactionCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'companyLocalCurrencyID' => $faker->randomDigitNotNull,
        'companyLocalCurrency' => $faker->word,
        'companyLocalExchangeRate' => $faker->randomDigitNotNull,
        'companyLocalCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'companyReportingCurrencyID' => $faker->randomDigitNotNull,
        'companyReportingCurrency' => $faker->word,
        'companyReportingExchangeRate' => $faker->randomDigitNotNull,
        'companyReportingCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'customerCurrencyID' => $faker->randomDigitNotNull,
        'customerCurrency' => $faker->word,
        'customerCurrencyExchangeRate' => $faker->randomDigitNotNull,
        'customerCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'segmentID' => $faker->randomDigitNotNull,
        'companyID' => $faker->randomDigitNotNull,
        'companyCode' => $faker->word,
        'customerReceivableAutoID' => $faker->randomDigitNotNull,
        'bankGLAutoID' => $faker->randomDigitNotNull,
        'bankCurrencyID' => $faker->randomDigitNotNull,
        'bankCurrency' => $faker->word,
        'bankCurrencyExchangeRate' => $faker->randomDigitNotNull,
        'bankCurrencyDecimalPlaces' => $faker->randomDigitNotNull,
        'bankCurrencyAmount' => $faker->randomDigitNotNull,
        'isVoid' => $faker->randomDigitNotNull,
        'voidBy' => $faker->randomDigitNotNull,
        'voidDatetime' => $faker->date('Y-m-d H:i:s'),
        'createdUserGroup' => $faker->randomDigitNotNull,
        'createdPCID' => $faker->word,
        'createdUserID' => $faker->word,
        'createdUserName' => $faker->word,
        'createdDateTime' => $faker->date('Y-m-d H:i:s'),
        'modifiedPCID' => $faker->word,
        'modifiedUserID' => $faker->word,
        'modifiedUserName' => $faker->word,
        'modifiedDateTime' => $faker->date('Y-m-d H:i:s'),
        'timestamp' => $faker->date('Y-m-d H:i:s'),
        'promotionID' => $faker->randomDigitNotNull,
        'promotiondiscount' => $faker->randomDigitNotNull,
        'promotiondiscountAmount' => $faker->randomDigitNotNull,
        'isPromotion' => $faker->randomDigitNotNull
    ];
});
