<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\TenderMasterReferred;
use Faker\Generator as Faker;

$factory->define(TenderMasterReferred::class, function (Faker $faker) {

    return [
        'id' => $faker->randomDigitNotNull,
        'title' => $faker->word,
        'title_sec_lang' => $faker->word,
        'description' => $faker->word,
        'description_sec_lang' => $faker->word,
        'tender_type_id' => $faker->randomDigitNotNull,
        'currency_id' => $faker->randomDigitNotNull,
        'envelop_type_id' => $faker->randomDigitNotNull,
        'procument_cat_id' => $faker->randomDigitNotNull,
        'procument_sub_cat_id' => $faker->randomDigitNotNull,
        'evaluation_type_id' => $faker->randomDigitNotNull,
        'estimated_value' => $faker->randomDigitNotNull,
        'allocated_budget' => $faker->randomDigitNotNull,
        'budget_document' => $faker->text,
        'tender_document_fee' => $faker->randomDigitNotNull,
        'bank_id' => $faker->randomDigitNotNull,
        'bank_account_id' => $faker->randomDigitNotNull,
        'document_sales_start_date' => $faker->date('Y-m-d H:i:s'),
        'document_sales_end_date' => $faker->date('Y-m-d H:i:s'),
        'pre_bid_clarification_start_date' => $faker->date('Y-m-d H:i:s'),
        'pre_bid_clarification_end_date' => $faker->date('Y-m-d H:i:s'),
        'pre_bid_clarification_method' => $faker->randomDigitNotNull,
        'site_visit_date' => $faker->date('Y-m-d H:i:s'),
        'site_visit_end_date' => $faker->date('Y-m-d H:i:s'),
        'bid_submission_opening_date' => $faker->date('Y-m-d H:i:s'),
        'bid_submission_closing_date' => $faker->date('Y-m-d H:i:s'),
        'created_at' => $faker->date('Y-m-d H:i:s'),
        'created_by' => $faker->randomDigitNotNull,
        'updated_at' => $faker->date('Y-m-d H:i:s'),
        'updated_by' => $faker->randomDigitNotNull,
        'deleted_at' => $faker->date('Y-m-d H:i:s'),
        'deleted_by' => $faker->randomDigitNotNull,
        'company_id' => $faker->randomDigitNotNull,
        'document_system_id' => $faker->randomDigitNotNull,
        'document_id' => $faker->word,
        'tender_code' => $faker->word,
        'serial_number' => $faker->randomDigitNotNull,
        'confirmed_yn' => $faker->randomDigitNotNull,
        'confirmed_by_emp_system_id' => $faker->randomDigitNotNull,
        'confirmed_by_name' => $faker->word,
        'confirmed_date' => $faker->date('Y-m-d H:i:s'),
        'approved' => $faker->randomDigitNotNull,
        'approved_date' => $faker->date('Y-m-d H:i:s'),
        'approved_by_user_system_id' => $faker->randomDigitNotNull,
        'approval_remarks' => $faker->word,
        'refferedBackYN' => $faker->randomDigitNotNull,
        'timesReferred' => $faker->randomDigitNotNull,
        'RollLevForApp_curr' => $faker->randomDigitNotNull,
        'approved_by_emp_name' => $faker->word,
        'published_yn' => $faker->randomDigitNotNull,
        'closed_yn' => $faker->randomDigitNotNull,
        'stage' => $faker->randomDigitNotNull,
        'no_of_alternative_solutions' => $faker->randomDigitNotNull,
        'commercial_weightage' => $faker->randomDigitNotNull,
        'technical_weightage' => $faker->randomDigitNotNull,
        'is_active_go_no_go' => $faker->randomDigitNotNull,
        'commercial_passing_weightage' => $faker->randomDigitNotNull,
        'technical_passing_weightage' => $faker->randomDigitNotNull,
        'min_approval_bid_opening' => $faker->randomDigitNotNull,
        'bid_opening_date' => $faker->date('Y-m-d H:i:s'),
        'bid_opening_end_date' => $faker->date('Y-m-d H:i:s'),
        'technical_bid_opening_date' => $faker->date('Y-m-d H:i:s'),
        'technical_bid_closing_date' => $faker->date('Y-m-d H:i:s'),
        'commerical_bid_opening_date' => $faker->date('Y-m-d H:i:s'),
        'commerical_bid_closing_date' => $faker->date('Y-m-d H:i:s'),
        'doc_verifiy_by_emp' => $faker->randomDigitNotNull,
        'doc_verifiy_date' => $faker->date('Y-m-d H:i:s'),
        'doc_verifiy_status' => $faker->word,
        'doc_verifiy_comment' => $faker->word,
        'published_at' => $faker->date('Y-m-d H:i:s'),
        'technical_eval_status' => $faker->word,
        'go_no_go_status' => $faker->word,
        'commercial_verify_status' => $faker->word,
        'commercial_verify_at' => $faker->date('Y-m-d H:i:s'),
        'commercial_verify_by' => $faker->randomDigitNotNull,
        'commercial_ranking_line_item_status' => $faker->word,
        'combined_ranking_status' => $faker->word,
        'is_awarded' => $faker->word,
        'award_comment' => $faker->word,
        'document_type' => $faker->randomDigitNotNull,
        'commercial_line_item_status' => $faker->word,
        'commercial_ranking_comment' => $faker->word,
        'final_tender_award_comment' => $faker->word,
        'final_tender_awarded' => $faker->word,
        'final_tender_award_email' => $faker->word,
        'award_commite_mem_status' => $faker->word,
        'final_tender_comment_status' => $faker->word,
        'tender_edit_version_id' => $faker->randomDigitNotNull,
        'is_negotiation_started' => $faker->randomDigitNotNull,
        'negotiation_published' => $faker->randomDigitNotNull,
        'negotiation_serial_no' => $faker->randomDigitNotNull,
        'negotiation_code' => $faker->word,
        'tender_edit_confirm_id' => $faker->randomDigitNotNull,
        'is_negotiation_closed' => $faker->randomDigitNotNull,
        'negotiation_commercial_ranking_line_item_status' => $faker->word,
        'negotiation_commercial_ranking_comment' => $faker->word,
        'negotiation_combined_ranking_status' => $faker->word,
        'negotiation_award_comment' => $faker->word,
        'negotiation_is_awarded' => $faker->word,
        'negotiation_doc_verify_comment' => $faker->word,
        'negotiation_doc_verify_status' => $faker->word,
        'show_technical_criteria' => $faker->randomDigitNotNull
    ];
});
