<?php
Route::get('attendance-clock-out', 'HRJobInvokeAPIController@clockOutDebug')->name('Attendance clock out');
Route::get('attendance-clock-in', 'HRJobInvokeAPIController@attendanceClockIn')->name('Attendance clock in');
Route::get('travel-request-notification', 'HRJobInvokeAPIController@sendTravelRequestNotifications')->name('Travel request notification');
Route::get('attendance-notification-debug', 'HRJobInvokeAPIController@attendance_notification_debug')->name('Attendance notification debug');
Route::get('birthdayWishesEmailDebug', 'HRJobInvokeAPIController@birthdayWishesEmailDebug')->name('Birthday wishes email debug');
Route::get('maximum-leave-carry-forward-debug', 'HRJobInvokeAPIController@maximumLeaveCarryForwardDebug')->name('Maximum leave carry forward debug');
Route::get('hr-document-notification', 'HRJobInvokeAPIController@sendHrDocNotifications')->name('HR document notification');
Route::get('return-to-work-notification', 'HRJobInvokeAPIController@sendReturnToWorkNotifications')->name('Return to work notification');
Route::get('employee-profile-creation-notification', 'HRJobInvokeAPIController@sendEmpProfileCreateNotifications')->name('Employee profile creation notification');
Route::get('hrNotificationDebug', 'HRJobInvokeAPIController@hrNotificationDebug')->name('HR notification debug');
Route::get('clockOutJobCall', 'HRJobInvokeAPIController@clockOutJobCall')->name('Clock out job call');
Route::get('crossDayClockOutJobCall', 'HRJobInvokeAPIController@crossDayClockOutJobCall')->name('Cross day clock out job call');
Route::get('crossDayClockOutDebug', 'HRJobInvokeAPIController@crossDayClockOutJobCallDebug')->name('Cross day clock out job call');
Route::get('leaveAccrualJobCallDebug', 'HRJobInvokeAPIController@leaveAccrualJobCallDebug')->name('Leave accrual job call debug');
Route::get('delegationJobCallDebug', 'HRJobInvokeAPIController@delegationJobCallDebug')->name('Delegation job call debug');
Route::get('empDesignationUpdateNotification', 'HRJobInvokeAPIController@sendEmpDesignationUpdateNotification')->name('Employee designation update notification');
Route::post('unconfirmed-attendance-pull', 'HRJobInvokeAPIController@unConfirmedAttendancePull')->name('Unconfirmed attendance pull');
Route::get('designation-create-update-notification', 'HRJobInvokeAPIController@designationCreateUpdateNotification')->name('Designation create update notification');
Route::get('employee-tasking-notification', 'HRJobInvokeAPIController@sendEmployeeTaskingNotifications')->name('Employee tasking notification');
Route::get('employee-movement-notification', 'HRJobInvokeAPIController@sendEmployeeMovementNotifications')->name('Employee movement notification');
