<?php

namespace App\Repositories;

use App\Models\SrpEmployeeDetails;
use InfyOm\Generator\Common\BaseRepository;

/**
 * Class SrpEmployeeDetailsRepository
 * @package App\Repositories
 * @version June 28, 2021, 2:07 pm +04
 *
 * @method SrpEmployeeDetails findWithoutFail($id, $columns = ['*'])
 * @method SrpEmployeeDetails find($id, $columns = ['*'])
 * @method SrpEmployeeDetails first($columns = ['*'])
*/
class SrpEmployeeDetailsRepository extends BaseRepository
{
    /**
     * @var array
     */
    protected $fieldSearchable = [
        'serialNo',
        'ECode',
        'EmpSecondaryCode',
        'EmpTitleId',
        'manPowerNo',
        'ssoNo',
        'EmpDesignationId',
        'Ename1',
        'Ename2',
        'AirportDestinationID',
        'Ename3',
        'Ename4',
        'empSecondName',
        'EFamilyName',
        'initial',
        'EmpShortCode',
        'Enameother1',
        'Enameother2',
        'Enameother3',
        'Enameother4',
        'empSecondNameOther',
        'EFamilyNameOther',
        'empSignature',
        'EmpImage',
        'EthumbnailImage',
        'Gender',
        'payee_emp_type',
        'EpAddress1',
        'EpAddress2',
        'EpAddress3',
        'EpAddress4',
        'ZipCode',
        'EpTelephone',
        'EpFax',
        'EpMobile',
        'EcAddress1',
        'EcAddress2',
        'EcAddress3',
        'EcAddress4',
        'EcPOBox',
        'EcPC',
        'EcArea',
        'EcTel',
        'EcExtension',
        'EcFax',
        'EcMobile',
        'EEmail',
        'personalEmail',
        'EDOB',
        'EDOJ',
        'NIC',
        'insuranceNo',
        'EPassportNO',
        'EPassportExpiryDate',
        'EVisaExpiryDate',
        'Nid',
        'Rid',
        'AirportDestination',
        'travelFrequencyID',
        'commissionSchemeID',
        'medicalInfo',
        'SchMasterId',
        'branchID',
        'userType',
        'isSystemUserYN',
        'UserName',
        'Password',
        'isDeleted',
        'HouseID',
        'HouseCatID',
        'HPID',
        'isPayrollEmployee',
        'payCurrencyID',
        'payCurrency',
        'isLeft',
        'DateLeft',
        'LeftComment',
        'BloodGroup',
        'DateAssumed',
        'probationPeriod',
        'isDischarged',
        'dischargedByEmpID',
        'EmployeeConType',
        'dischargedDate',
        'lastWorkingDate',
        'gratuityCalculationDate',
        'dischargeTypeID',
        'dischargeReasonID',
        'dischargedComment',
        'eligibleToRehire',
        'finalSettlementDoneYN',
        'MaritialStatus',
        'Nationality',
        'isLoginAttempt',
        'isChangePassword',
        'CreatedUserName',
        'CreatedDate',
        'CreatedPC',
        'ModifiedUserName',
        'Timestamp',
        'ModifiedPC',
        'isActive',
        'NoOfLoginAttempt',
        'languageID',
        'locationID',
        'sponsorID',
        'mobileCreditLimit',
        'segmentID',
        'Erp_companyID',
        'insurance_category',
        'insurance_code',
        'cover_from',
        'cover_to',
        'floorID',
        'deviceID',
        'empMachineID',
        'leaveGroupID',
        'isMobileCheckIn',
        'isCheckin',
        'token',
        'overTimeGroup',
        'familyStatusID',
        'gratuityID',
        'isSystemAdmin',
        'isHRAdmin',
        'contractStartDate',
        'contractEndDate',
        'contractRefNo',
        'empConfirmDate',
        'empConfirmedYN',
        'rejoinDate',
        'previousEmpID',
        'gradeID',
        'pos_userGroupMasterID',
        'pos_userGroupMasterID_gpos',
        'pos_barCode',
        'isLocalPosSyncEnable',
        'isLocalPosSalesRptEnable',
        'tibianType',
        'LocalPOSUserType',
        'last_login',
        'exclude_PASI'
    ];

    /**
     * Configure the Model
     **/
    public function model()
    {
        return SrpEmployeeDetails::class;
    }
}
